### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by TahsinTariq** [wildiness/NodeSharer#6]
Getting this error while trying to install on blender 2.91

```
Traceback (most recent call last):
  File "/work/blender-2.91.0-linux64/2.91/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'NodeSharer-0'
```
/work is my mounted ssd...

I'm on pop-os 20.04

**Comment by wildiness** [comment]
Ok, I can reproduce this bug. It seems like blender strips everything past the first dot in the filename when enabling it. The release download folder is named "NodeSharer-0.2.0" and the last ".2.0" get removed by Blender. 

Fix:
Download the addon again like described in the installation instruction step 1. But do not download it from the releases page. I will also disable the releases page.

Thank you for the bug report. I should have tested it more thoroughly.

**Comment by TahsinTariq** [comment]
Thank you so much for the quick response. It works.
